// import PushNotification from 'react-native-push-notification';
// import { PushNotificationIOS } from 'react-native';

// const pushNotification = () => {
//  PushNotification.configure({

//    onRegister: function(token) {
//      //process token
//      console.log("PushNotification, TOKEN:", token);
//    },

//    onNotification: function(notification) {
//     console.log("PushNotification, notification:", notification);
//      // process the notification
//      // required on iOS only
//      //notification.finish(PushNotificationIOS.FetchResult.NoData);
//    },

//    permissions: {
//      alert: true,
//      badge: true,
//      sound: true
//    },

//    popInitialNotification: true,
//    requestPermissions: true,
//  });
// };



// export {
//     pushNotification,
// };

// handlePushNotification() {
//     let title = "Sap Den Han Dang Kiem!";
//     let message = "Xe 30E-12345 con 10 ngay nua la den han dang kiem. Xe 18L-23456 con 5 ngay Nua la den han.";
//     if (Platform.OS == 'ios') {
//         console.log("handlePushNotification iOS")
//         PushNotification.localNotification({
//         /* iOS only properties */
//         //alertAction: // (optional) default: view
//         //category: // (optional) default: null
//         //userInfo: // (optional) default: null (object containing additional notification data)

//         /* iOS and Android properties */
//         title: title, // (optional)
//         message: message, // (required)
//         playSound: true, // (optional) default: true
//         soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
//         number: '10', // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
//         repeatType: 'day', // (optional) Repeating interval. Check 'Repeating Notifications' section for more info.
//         });
//     } else {
//         console.log("handlePushNotification Android")
//         PushNotification.localNotification({
//         /* Android Only Properties */
//         //id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
//         ticker: "My Notification Ticker", // (optional)
//         autoCancel: true, // (optional) default: true
//         largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
//         smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
//         //bigText: "My big text that will be shown when notification is expanded", // (optional) default: "message" prop
//         //subText: "This is a subText", // (optional) default: none
//         //color: "red", // (optional) default: system default
//         vibrate: true, // (optional) default: true
//         vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
//         //tag: 'some_tag', // (optional) add tag to message
//         //group: "group", // (optional) add group to message
//         //ongoing: false, // (optional) set whether this is an "ongoing" notification
//         priority: "high", // (optional) set notification priority, default: high
//         visibility: "public", // (optional) set notification visibility, default: private
//         importance: "high", // (optional) set notification importance, default: high

//         /* iOS and Android properties */
//         title: title, // (optional)
//         message: message, // (required)
//         playSound: true, // (optional) default: true
//         soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
//         number: '10', // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
//         repeatType: 'day', // (optional) Repeating interval. Check 'Repeating Notifications' section for more info.
//         actions: '["Yes", "No"]',  // (Android only) See the doc for notification actions to know more
//         });
//     }
// }